# utils/codes_ald.py
# ============================================================
# Referentiel des codes ALD (Affection de Longue Duree) -- "LISTE DES
# AFFECTIONS DE LONGUE DUREE PAR SPECIALITE" fournie par le patron
# (2026-10-02), valable pour CNSS et INAM (patron : "la fiche ald que je
# vais envoyer est valable pour inam et cnss"). Utilise dans le formulaire
# TPC (templates/amu_tpc.html) : la recherche se fait par nom de l'affection
# (patron : "c'est le code seulement on veut dans la colonne meme si la
# recherche se fait par nom de l'affection"), le code_ald correspondant se
# remplit automatiquement a la selection.
#
# Une meme pathologie apparait parfois sous son libelle general ET sous
# chacune de ses variantes specifiques (ex: "Insuffisance cardiaque"
# (ALD001) et "Insuffisance ventriculaire gauche" (ALD001 aussi)) -- les
# deux sont cherchables, volontairement, pour coller a la facon dont un
# medecin peut nommer le diagnostic.
# ============================================================

CODES_ALD = [
    {"affection": "Insuffisance cardiaque", "code_ald": "ALD001", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Insuffisance ventriculaire gauche", "code_ald": "ALD001", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Insuffisance ventriculaire droite secondaire", "code_ald": "ALD001", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Troubles permanents du rythme et de la conduction", "code_ald": "ALD002", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Troubles de la conduction (BAV complet)", "code_ald": "ALD002", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Arythmie complète par fibrillation auriculaire installée", "code_ald": "ALD002", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Troubles du rythme supraventriculaires ou ventriculaires récidivants", "code_ald": "ALD002", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Valvulopathies rhumatismales", "code_ald": "ALD003", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Mono-valvulopathie mitrale", "code_ald": "ALD003", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Mono-valvulopathie Aortique", "code_ald": "ALD003", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Mono-valvulopathie Tricuspidienne", "code_ald": "ALD003", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Polyvalvulopathie", "code_ald": "ALD003", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Cardiopathie congénitale", "code_ald": "ALD004", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Transposition des gros vaisseaux", "code_ald": "ALD004", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Tétralogie de Fallot", "code_ald": "ALD004", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Coarctation de l'Aorte", "code_ald": "ALD004", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Communication Interventriculaire", "code_ald": "ALD004", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Persistance du canal artériel", "code_ald": "ALD004", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Artériopathies chroniques", "code_ald": "ALD005", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Hypertension artérielle", "code_ald": "ALD006", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Cardiopathie ischémique", "code_ald": "ALD007", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Angor stable ou instable", "code_ald": "ALD007", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Suites d'infarctus du Myocarde aigu", "code_ald": "ALD007", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Insuffisance veineuse chronique", "code_ald": "ALD043", "chapitre": "Maladies Cardio-vasculaires"},
    {"affection": "Diabète insulino-dépendant", "code_ald": "ALD008", "chapitre": "Maladies métaboliques et endocriniennes"},
    {"affection": "Diabète de type 1 (DID)", "code_ald": "ALD008", "chapitre": "Maladies métaboliques et endocriniennes"},
    {"affection": "Diabète non insulino-dépendant", "code_ald": "ALD009", "chapitre": "Maladies métaboliques et endocriniennes"},
    {"affection": "Diabète de type 2 (DNID)", "code_ald": "ALD009", "chapitre": "Maladies métaboliques et endocriniennes"},
    {"affection": "Hypothyroidie-Hyperthyroidie", "code_ald": "ALD053", "chapitre": "Maladies métaboliques et endocriniennes"},
    {"affection": "Hypothyroidie-Hyperthyroidie", "code_ald": "ALD053", "chapitre": "Maladies métaboliques et endocriniennes"},
    {"affection": "Insuffisance rénale chronique", "code_ald": "ALD010", "chapitre": "Maladies néphrologiques"},
    {"affection": "Insuffisance rénale chronique / terminale", "code_ald": "ALD010", "chapitre": "Maladies néphrologiques"},
    {"affection": "Néphropathies chroniques", "code_ald": "ALD011", "chapitre": "Maladies néphrologiques"},
    {"affection": "Néphropathies héréditaires ou congénitales", "code_ald": "ALD011", "chapitre": "Maladies néphrologiques"},
    {"affection": "Glomérulonéphrites", "code_ald": "ALD011", "chapitre": "Maladies néphrologiques"},
    {"affection": "Néphropathies interstitielles", "code_ald": "ALD011", "chapitre": "Maladies néphrologiques"},
    {"affection": "Néphropathies vasculaires", "code_ald": "ALD011", "chapitre": "Maladies néphrologiques"},
    {"affection": "Syndromes néphrotiques", "code_ald": "ALD012", "chapitre": "Maladies néphrologiques"},
    {"affection": "Affections neurologiques et neuromusculaires chroniques", "code_ald": "ALD013", "chapitre": "Maladies neurologiques"},
    {"affection": "Hérédo ataxies", "code_ald": "ALD013", "chapitre": "Maladies neurologiques"},
    {"affection": "Polyradiculonévrites", "code_ald": "ALD013", "chapitre": "Maladies neurologiques"},
    {"affection": "Myasthénie", "code_ald": "ALD013", "chapitre": "Maladies neurologiques"},
    {"affection": "Myopathies", "code_ald": "ALD013", "chapitre": "Maladies neurologiques"},
    {"affection": "Suites d'accident vasculaire cérébral ou médullaire ischémique ou hémorragique", "code_ald": "ALD014", "chapitre": "Maladies neurologiques"},
    {"affection": "Suites d'AVC ischémique ou hémorragique", "code_ald": "ALD014", "chapitre": "Maladies neurologiques"},
    {"affection": "Suites d'accident vasculaire médullaire ischémique ou hémorragique", "code_ald": "ALD014", "chapitre": "Maladies neurologiques"},
    {"affection": "Epilepsie", "code_ald": "ALD015", "chapitre": "Maladies neurologiques"},
    {"affection": "Epilepsie grave", "code_ald": "ALD015", "chapitre": "Maladies neurologiques"},
    {"affection": "Etat de grand mal épileptique", "code_ald": "ALD015", "chapitre": "Maladies neurologiques"},
    {"affection": "Maladie de Parkinson", "code_ald": "ALD016", "chapitre": "Maladies neurologiques"},
    {"affection": "Sclérose en plaques", "code_ald": "ALD017", "chapitre": "Maladies neurologiques"},
    {"affection": "Toxoplasmose cérébrale", "code_ald": "ALD048", "chapitre": "Maladies neurologiques"},
    {"affection": "Anémies hémolytiques chroniques", "code_ald": "ALD018", "chapitre": "Maladies du sang"},
    {"affection": "Thalassémies majeures", "code_ald": "ALD018", "chapitre": "Maladies du sang"},
    {"affection": "Drépanocytoses homozygotes", "code_ald": "ALD018", "chapitre": "Maladies du sang"},
    {"affection": "Anémies hémolytiques auto-immunes chroniques", "code_ald": "ALD018", "chapitre": "Maladies du sang"},
    {"affection": "Aplasie médullaire globale", "code_ald": "ALD019", "chapitre": "Maladies du sang"},
    {"affection": "Myélodysplasies", "code_ald": "ALD020", "chapitre": "Maladies du sang"},
    {"affection": "Anémie réfractaire", "code_ald": "ALD020", "chapitre": "Maladies du sang"},
    {"affection": "Anémie réfractaire sidéroblastique", "code_ald": "ALD020", "chapitre": "Maladies du sang"},
    {"affection": "Myélodysplasies", "code_ald": "ALD021", "chapitre": "Maladies du sang"},
    {"affection": "Anémie réfractaire avec excès de blastes", "code_ald": "ALD021", "chapitre": "Maladies du sang"},
    {"affection": "Leucémie myélomonocytaire chronique", "code_ald": "ALD021", "chapitre": "Maladies du sang"},
    {"affection": "Troubles héréditaires de l'hémostase", "code_ald": "ALD021", "chapitre": "Maladies du sang"},
    {"affection": "Maladie de Willebrand", "code_ald": "ALD021", "chapitre": "Maladies du sang"},
    {"affection": "Hémophilie majeure", "code_ald": "ALD021", "chapitre": "Maladies du sang"},
    {"affection": "Hépatites chroniques actives du foie (hépatite B et C)", "code_ald": "ALD022", "chapitre": "Maladies du foie"},
    {"affection": "Hépatite B ou C", "code_ald": "ALD022", "chapitre": "Maladies du foie"},
    {"affection": "Cirrhoses du foie", "code_ald": "ALD023", "chapitre": "Maladies du foie"},
    {"affection": "Syndrome d'Immunodéficience Acquise (SIDA)", "code_ald": "ALD024", "chapitre": "Maladies infectieuses"},
    {"affection": "Insuffisance respiratoire chronique", "code_ald": "ALD025", "chapitre": "Maladies respiratoires"},
    {"affection": "Insuffisance respiratoire sévère", "code_ald": "ALD025", "chapitre": "Maladies respiratoires"},
    {"affection": "Décompensation aigue des insuffisances respiratoires chroniques", "code_ald": "ALD025", "chapitre": "Maladies respiratoires"},
    {"affection": "Asthme", "code_ald": "ALD026", "chapitre": "Maladies respiratoires"},
    {"affection": "Asthme chronique modéré ou sévère", "code_ald": "ALD026", "chapitre": "Maladies respiratoires"},
    {"affection": "Episodes sévères d'asthme", "code_ald": "ALD026", "chapitre": "Maladies respiratoires"},
    {"affection": "Vascularites", "code_ald": "ALD027", "chapitre": "Maladies systémiques"},
    {"affection": "Périartérite Noueuse", "code_ald": "ALD027", "chapitre": "Maladies systémiques"},
    {"affection": "Maladie de Behçet", "code_ald": "ALD027", "chapitre": "Maladies systémiques"},
    {"affection": "Maladie de Wegener", "code_ald": "ALD027", "chapitre": "Maladies systémiques"},
    {"affection": "Lupus érythémateux aïgu disséminé", "code_ald": "ALD028", "chapitre": "Maladies systémiques"},
    {"affection": "Sclérodermie généralisée évolutive", "code_ald": "ALD029", "chapitre": "Maladies systémiques"},
    {"affection": "Polyarthrite rhumatoïde évolutive", "code_ald": "ALD030", "chapitre": "Maladies systémiques"},
    {"affection": "Polyarthrite rhumatoïde", "code_ald": "ALD030", "chapitre": "Maladies systémiques"},
    {"affection": "Spondylarthrite ankylosante", "code_ald": "ALD031", "chapitre": "Maladies systémiques"},
    {"affection": "Spondylarthropathie", "code_ald": "ALD049", "chapitre": "Maladies rhumatismales inflammatoires"},
    {"affection": "Goutte", "code_ald": "ALD042", "chapitre": "Maladies rhumatismales inflammatoires"},
    {"affection": "Pemphigus", "code_ald": "ALD052", "chapitre": "Maladies rhumatismales inflammatoires"},
    {"affection": "Rhumatisme psoriasique", "code_ald": "ALD050", "chapitre": "Maladies rhumatismales inflammatoires"},
    {"affection": "Algodystrophie", "code_ald": "ALD051", "chapitre": "Maladies rhumatismales inflammatoires"},
    {"affection": "Psychoses", "code_ald": "ALD032", "chapitre": "Maladies rhumatismales inflammatoires"},
    {"affection": "Schizophrénies", "code_ald": "ALD032", "chapitre": "Maladies rhumatismales inflammatoires"},
    {"affection": "Psychoses infantiles", "code_ald": "ALD032", "chapitre": "Maladies rhumatismales inflammatoires"},
    {"affection": "Troubles personnalité chroniques de la personnalité", "code_ald": "ALD033", "chapitre": "Maladies mentales"},
    {"affection": "Personnalité pathologique", "code_ald": "ALD033", "chapitre": "Maladies mentales"},
    {"affection": "Troubles addictifs", "code_ald": "ALD033", "chapitre": "Maladies mentales"},
    {"affection": "Etat dépressif", "code_ald": "ALD033", "chapitre": "Maladies mentales"},
    {"affection": "Trouble névrotique", "code_ald": "ALD033", "chapitre": "Maladies mentales"},
    {"affection": "Etat de déficit mental", "code_ald": "ALD034", "chapitre": "Maladies mentales"},
    {"affection": "Démences acquises", "code_ald": "ALD034", "chapitre": "Maladies mentales"},
    {"affection": "Retard mental", "code_ald": "ALD034", "chapitre": "Maladies mentales"},
    {"affection": "Rectocolite hémorragique évolutive", "code_ald": "ALD035", "chapitre": "Maladies du tube digestif"},
    {"affection": "Maladie de Crohn évolutive", "code_ald": "ALD036", "chapitre": "Maladies du tube digestif"},
    {"affection": "Colopathie fonctionnelle", "code_ald": "ALD044", "chapitre": "Maladies du tube digestif"},
    {"affection": "Tumeurs malignes de tout appareil/organe", "code_ald": "ALD037", "chapitre": "Tumeurs malignes"},
    {"affection": "Affections malignes du tissu", "code_ald": "ALD038", "chapitre": "Affections malignes du tissu lymphatique ou hématopoique"},
    {"affection": "Maladie d'Hodgkin", "code_ald": "ALD038", "chapitre": "Affections malignes du tissu lymphatique ou hématopoique"},
    {"affection": "Affections malignes du tissu lymphatique ou hématopoïétique", "code_ald": "ALD038", "chapitre": "Affections malignes du tissu lymphatique ou hématopoique"},
    {"affection": "Lymphome diffus non hodgkinien", "code_ald": "ALD038", "chapitre": "Affections malignes du tissu lymphatique ou hématopoique"},
    {"affection": "Leucémie Myéloïde", "code_ald": "ALD038", "chapitre": "Affections malignes du tissu lymphatique ou hématopoique"},
    {"affection": "Glaucome chronique", "code_ald": "ALD039", "chapitre": "Maladies ophtalmiques"},
    {"affection": "Rétinopathie diabétique", "code_ald": "ALD040", "chapitre": "Maladies ophtalmiques"},
    {"affection": "Conjonctivite chronique allergique", "code_ald": "ALD041", "chapitre": "Maladies ophtalmiques"},
    {"affection": "Polypose nasosinusienne", "code_ald": "ALD045", "chapitre": "Maladies ORL"},
    {"affection": "Rhinite allergique", "code_ald": "ALD046", "chapitre": "Maladies ORL"},
    {"affection": "Otite chronique", "code_ald": "ALD047", "chapitre": "Maladies ORL"},
]
